# Generated by Django 2.2 on 2020-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('Lagos', 'Lagos'), ('Port-Harcourt', 'Port-Harcourt'), ('Kaduna', 'Kaduna'), ('Jos', 'Jos'), ('Abuja', 'Abuja')], max_length=20)),
                ('hotel', models.CharField(max_length=100)),
                ('resturant', models.CharField(max_length=100)),
                ('popular_event', models.CharField(blank=True, max_length=100, null=True)),
                ('tourist_center', models.CharField(max_length=100)),
                ('trip_plan', models.CharField(choices=[('Tour', 'Tour'), ('Vacation', 'Vacation'), ('Conference', 'Conference'), ('Event', 'Event'), ('Party', 'Party')], max_length=10)),
                ('attendee', models.CharField(choices=[('single', 'single'), ('couple', 'couple'), ('family', 'family'), ('friends', 'friends'), ('co-workers', 'co-workers')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
