# Generated by Django 2.2 on 2020-02-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200217_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Travel',
        ),
    ]
